// data.js : 拡張版（365日分）

window.shinData = {
  oracles: [
    { oracle: "静、兆しを孕む。", interpretation: "古き縁が今を導く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "心、波立つこと勿れ。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "風、北より来たる。", interpretation: "争わず、ただ佇むが良い。", translation: "Truth lies in the quiet." },
    { oracle: "夢、深き淵に在り。", interpretation: "今は心静かに、機を待て。", translation: "Your thoughts have already reached their destination." },
    { oracle: "夢、深き淵に在り。", interpretation: "古き縁が今を導く。", translation: "Silence will guide you to the answer." },
    { oracle: "星、流れて示すは縁。", interpretation: "歩みを止めるな。", translation: "Old ties will guide your present." },
    { oracle: "星、流れて示すは縁。", interpretation: "慎重さが運を招く。", translation: "Truth lies in the quiet." },
    { oracle: "星、流れて示すは縁。", interpretation: "今は心静かに、機を待て。", translation: "Truth lies in the quiet." },
    { oracle: "神、内に宿る。", interpretation: "今は心静かに、機を待て。", translation: "Your thoughts have already reached their destination." },
    { oracle: "星、流れて示すは縁。", interpretation: "行動よりも内観の時。", translation: "Wait patiently for the right moment." },
    { oracle: "星、流れて示すは縁。", interpretation: "思いはすでに届いている。", translation: "Your thoughts have already reached their destination." },
    { oracle: "水、形なくして道を知る。", interpretation: "今は心静かに、機を待て。", translation: "It is time for reflection, not action." },
    { oracle: "夢、深き淵に在り。", interpretation: "古き縁が今を導く。", translation: "Wait patiently for the right moment." },
    { oracle: "心、波立つこと勿れ。", interpretation: "古き縁が今を導く。", translation: "Truth lies in the quiet." },
    { oracle: "神、内に宿る。", interpretation: "行動よりも内観の時。", translation: "Your thoughts have already reached their destination." },
    { oracle: "夢、深き淵に在り。", interpretation: "慎重さが運を招く。", translation: "It is time for reflection, not action." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "行動よりも内観の時。", translation: "Silence will guide you to the answer." },
    { oracle: "夢、深き淵に在り。", interpretation: "慎重さが運を招く。", translation: "It is time for reflection, not action." },
    { oracle: "月、影を照らす。", interpretation: "歩みを止めるな。", translation: "Your thoughts have already reached their destination." },
    { oracle: "神、問いを与う。", interpretation: "歩みを止めるな。", translation: "It is time for reflection, not action." },
    { oracle: "言、慎めば吉。", interpretation: "一歩進めば風が変わる。", translation: "Caution will lead to fortune." },
    { oracle: "風、北より来たる。", interpretation: "今は心静かに、機を待て。", translation: "Take one step forward, and the winds will change." },
    { oracle: "水、形なくして道を知る。", interpretation: "沈黙が答えを導く。", translation: "Old ties will guide your present." },
    { oracle: "炎、内より燃ゆ。", interpretation: "行動よりも内観の時。", translation: "Stand still without conflict." },
    { oracle: "静、兆しを孕む。", interpretation: "今は心静かに、機を待て。", translation: "Do not stop your steps." },
    { oracle: "水、形なくして道を知る。", interpretation: "古き縁が今を導く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "夢、深き淵に在り。", interpretation: "今は心静かに、機を待て。", translation: "It is time for reflection, not action." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "行動よりも内観の時。", translation: "Caution will lead to fortune." },
    { oracle: "心、波立つこと勿れ。", interpretation: "古き縁が今を導く。", translation: "Stand still without conflict." },
    { oracle: "炎、内より燃ゆ。", interpretation: "真理は静けさの中にある。", translation: "Caution will lead to fortune." },
    { oracle: "静、兆しを孕む。", interpretation: "真理は静けさの中にある。", translation: "Old ties will guide your present." },
    { oracle: "風、北より来たる。", interpretation: "争わず、ただ佇むが良い。", translation: "Take one step forward, and the winds will change." },
    { oracle: "言、慎めば吉。", interpretation: "歩みを止めるな。", translation: "Silence will guide you to the answer." },
    { oracle: "水、形なくして道を知る。", interpretation: "沈黙が答えを導く。", translation: "Old ties will guide your present." },
    { oracle: "言、慎めば吉。", interpretation: "古き縁が今を導く。", translation: "Truth lies in the quiet." },
    { oracle: "言、慎めば吉。", interpretation: "真理は静けさの中にある。", translation: "Your thoughts have already reached their destination." },
    { oracle: "空、声なき声を放つ。", interpretation: "歩みを止めるな。", translation: "Wait patiently for the right moment." },
    { oracle: "言、慎めば吉。", interpretation: "思いはすでに届いている。", translation: "Your thoughts have already reached their destination." },
    { oracle: "心、波立つこと勿れ。", interpretation: "歩みを止めるな。", translation: "Do not stop your steps." },
    { oracle: "言、慎めば吉。", interpretation: "争わず、ただ佇むが良い。", translation: "Truth lies in the quiet." },
    { oracle: "心、波立つこと勿れ。", interpretation: "行動よりも内観の時。", translation: "Silence will guide you to the answer." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "一歩進めば風が変わる。", translation: "Wait patiently for the right moment." },
    { oracle: "炎、内より燃ゆ。", interpretation: "慎重さが運を招く。", translation: "Silence will guide you to the answer." },
    { oracle: "星、流れて示すは縁。", interpretation: "思いはすでに届いている。", translation: "Your thoughts have already reached their destination." },
    { oracle: "月、影を照らす。", interpretation: "歩みを止めるな。", translation: "Old ties will guide your present." },
    { oracle: "炎、内より燃ゆ。", interpretation: "争わず、ただ佇むが良い。", translation: "Stand still without conflict." },
    { oracle: "夢、深き淵に在り。", interpretation: "歩みを止めるな。", translation: "Silence will guide you to the answer." },
    { oracle: "星、流れて示すは縁。", interpretation: "歩みを止めるな。", translation: "Do not stop your steps." },
    { oracle: "水、形なくして道を知る。", interpretation: "沈黙が答えを導く。", translation: "Stand still without conflict." },
    { oracle: "心、波立つこと勿れ。", interpretation: "今は心静かに、機を待て。", translation: "Old ties will guide your present." },
    { oracle: "神、内に宿る。", interpretation: "一歩進めば風が変わる。", translation: "Wait patiently for the right moment." },
    { oracle: "月、影を照らす。", interpretation: "沈黙が答えを導く。", translation: "Old ties will guide your present." },
    { oracle: "炎、内より燃ゆ。", interpretation: "争わず、ただ佇むが良い。", translation: "Caution will lead to fortune." },
    { oracle: "風、北より来たる。", interpretation: "争わず、ただ佇むが良い。", translation: "It is time for reflection, not action." },
    { oracle: "星、流れて示すは縁。", interpretation: "思いはすでに届いている。", translation: "Do not stop your steps." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "真理は静けさの中にある。", translation: "It is time for reflection, not action." },
    { oracle: "炎、内より燃ゆ。", interpretation: "思いはすでに届いている。", translation: "It is time for reflection, not action." },
    { oracle: "空、声なき声を放つ。", interpretation: "行動よりも内観の時。", translation: "Your thoughts have already reached their destination." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "沈黙が答えを導く。", translation: "Wait patiently for the right moment." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "歩みを止めるな。", translation: "Stand still without conflict." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Do not stop your steps." },
    { oracle: "言、慎めば吉。", interpretation: "今は心静かに、機を待て。", translation: "Old ties will guide your present." },
    { oracle: "神、内に宿る。", interpretation: "沈黙が答えを導く。", translation: "Do not stop your steps." },
    { oracle: "星、流れて示すは縁。", interpretation: "真理は静けさの中にある。", translation: "Wait patiently for the right moment." },
    { oracle: "月、影を照らす。", interpretation: "思いはすでに届いている。", translation: "Stand still without conflict." },
    { oracle: "神、問いを与う。", interpretation: "一歩進めば風が変わる。", translation: "Truth lies in the quiet." },
    { oracle: "神、問いを与う。", interpretation: "一歩進めば風が変わる。", translation: "Stand still without conflict." },
    { oracle: "空、声なき声を放つ。", interpretation: "慎重さが運を招く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "水、形なくして道を知る。", interpretation: "争わず、ただ佇むが良い。", translation: "Your thoughts have already reached their destination." },
    { oracle: "星、流れて示すは縁。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "神、問いを与う。", interpretation: "歩みを止めるな。", translation: "Truth lies in the quiet." },
    { oracle: "月、影を照らす。", interpretation: "歩みを止めるな。", translation: "It is time for reflection, not action." },
    { oracle: "心、波立つこと勿れ。", interpretation: "行動よりも内観の時。", translation: "Truth lies in the quiet." },
    { oracle: "静、兆しを孕む。", interpretation: "真理は静けさの中にある。", translation: "Wait patiently for the right moment." },
    { oracle: "星、流れて示すは縁。", interpretation: "今は心静かに、機を待て。", translation: "Old ties will guide your present." },
    { oracle: "月、影を照らす。", interpretation: "一歩進めば風が変わる。", translation: "Take one step forward, and the winds will change." },
    { oracle: "月、影を照らす。", interpretation: "慎重さが運を招く。", translation: "It is time for reflection, not action." },
    { oracle: "言、慎めば吉。", interpretation: "歩みを止めるな。", translation: "Caution will lead to fortune." },
    { oracle: "月、影を照らす。", interpretation: "一歩進めば風が変わる。", translation: "It is time for reflection, not action." },
    { oracle: "心、波立つこと勿れ。", interpretation: "争わず、ただ佇むが良い。", translation: "Do not stop your steps." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Silence will guide you to the answer." },
    { oracle: "夢、深き淵に在り。", interpretation: "行動よりも内観の時。", translation: "Old ties will guide your present." },
    { oracle: "神、内に宿る。", interpretation: "争わず、ただ佇むが良い。", translation: "Old ties will guide your present." },
    { oracle: "夢、深き淵に在り。", interpretation: "真理は静けさの中にある。", translation: "Wait patiently for the right moment." },
    { oracle: "月、影を照らす。", interpretation: "沈黙が答えを導く。", translation: "Do not stop your steps." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "今は心静かに、機を待て。", translation: "Stand still without conflict." },
    { oracle: "静、兆しを孕む。", interpretation: "古き縁が今を導く。", translation: "Truth lies in the quiet." },
    { oracle: "炎、内より燃ゆ。", interpretation: "行動よりも内観の時。", translation: "Silence will guide you to the answer." },
    { oracle: "神、内に宿る。", interpretation: "一歩進めば風が変わる。", translation: "Stand still without conflict." },
    { oracle: "心、波立つこと勿れ。", interpretation: "沈黙が答えを導く。", translation: "It is time for reflection, not action." },
    { oracle: "空、声なき声を放つ。", interpretation: "歩みを止めるな。", translation: "Old ties will guide your present." },
    { oracle: "心、波立つこと勿れ。", interpretation: "慎重さが運を招く。", translation: "Old ties will guide your present." },
    { oracle: "心、波立つこと勿れ。", interpretation: "真理は静けさの中にある。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "星、流れて示すは縁。", interpretation: "今は心静かに、機を待て。", translation: "Do not stop your steps." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "静、兆しを孕む。", interpretation: "一歩進めば風が変わる。", translation: "Silence will guide you to the answer." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "沈黙が答えを導く。", translation: "Stand still without conflict." },
    { oracle: "心、波立つこと勿れ。", interpretation: "古き縁が今を導く。", translation: "Do not stop your steps." },
    { oracle: "心、波立つこと勿れ。", interpretation: "真理は静けさの中にある。", translation: "Take one step forward, and the winds will change." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "争わず、ただ佇むが良い。", translation: "Old ties will guide your present." },
    { oracle: "神、内に宿る。", interpretation: "行動よりも内観の時。", translation: "Wait patiently for the right moment." },
    { oracle: "神、内に宿る。", interpretation: "争わず、ただ佇むが良い。", translation: "Wait patiently for the right moment." },
    { oracle: "時、未だ満ちず。", interpretation: "行動よりも内観の時。", translation: "Stand still without conflict." },
    { oracle: "言、慎めば吉。", interpretation: "沈黙が答えを導く。", translation: "Truth lies in the quiet." },
    { oracle: "神、問いを与う。", interpretation: "今は心静かに、機を待て。", translation: "Your thoughts have already reached their destination." },
    { oracle: "月、影を照らす。", interpretation: "歩みを止めるな。", translation: "Stand still without conflict." },
    { oracle: "星、流れて示すは縁。", interpretation: "思いはすでに届いている。", translation: "Old ties will guide your present." },
    { oracle: "心、波立つこと勿れ。", interpretation: "行動よりも内観の時。", translation: "Caution will lead to fortune." },
    { oracle: "時、未だ満ちず。", interpretation: "沈黙が答えを導く。", translation: "Caution will lead to fortune." },
    { oracle: "静、兆しを孕む。", interpretation: "思いはすでに届いている。", translation: "Old ties will guide your present." },
    { oracle: "星、流れて示すは縁。", interpretation: "歩みを止めるな。", translation: "Old ties will guide your present." },
    { oracle: "星、流れて示すは縁。", interpretation: "慎重さが運を招く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "月、影を照らす。", interpretation: "一歩進めば風が変わる。", translation: "Do not stop your steps." },
    { oracle: "水、形なくして道を知る。", interpretation: "歩みを止めるな。", translation: "Wait patiently for the right moment." },
    { oracle: "神、問いを与う。", interpretation: "思いはすでに届いている。", translation: "Take one step forward, and the winds will change." },
    { oracle: "神、内に宿る。", interpretation: "行動よりも内観の時。", translation: "Wait patiently for the right moment." },
    { oracle: "心、波立つこと勿れ。", interpretation: "真理は静けさの中にある。", translation: "Caution will lead to fortune." },
    { oracle: "夢、深き淵に在り。", interpretation: "歩みを止めるな。", translation: "Stand still without conflict." },
    { oracle: "時、未だ満ちず。", interpretation: "真理は静けさの中にある。", translation: "Take one step forward, and the winds will change." },
    { oracle: "空、声なき声を放つ。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "夢、深き淵に在り。", interpretation: "一歩進めば風が変わる。", translation: "Wait patiently for the right moment." },
    { oracle: "炎、内より燃ゆ。", interpretation: "行動よりも内観の時。", translation: "Stand still without conflict." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "慎重さが運を招く。", translation: "Caution will lead to fortune." },
    { oracle: "月、影を照らす。", interpretation: "争わず、ただ佇むが良い。", translation: "Your thoughts have already reached their destination." },
    { oracle: "時、未だ満ちず。", interpretation: "今は心静かに、機を待て。", translation: "Truth lies in the quiet." },
    { oracle: "時、未だ満ちず。", interpretation: "真理は静けさの中にある。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "思いはすでに届いている。", translation: "Your thoughts have already reached their destination." },
    { oracle: "水、形なくして道を知る。", interpretation: "争わず、ただ佇むが良い。", translation: "Your thoughts have already reached their destination." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "心、波立つこと勿れ。", interpretation: "今は心静かに、機を待て。", translation: "Caution will lead to fortune." },
    { oracle: "静、兆しを孕む。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "水、形なくして道を知る。", interpretation: "歩みを止めるな。", translation: "Wait patiently for the right moment." },
    { oracle: "風、北より来たる。", interpretation: "歩みを止めるな。", translation: "Do not stop your steps." },
    { oracle: "夢、深き淵に在り。", interpretation: "思いはすでに届いている。", translation: "Old ties will guide your present." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "思いはすでに届いている。", translation: "Wait patiently for the right moment." },
    { oracle: "言、慎めば吉。", interpretation: "行動よりも内観の時。", translation: "Silence will guide you to the answer." },
    { oracle: "月、影を照らす。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "夢、深き淵に在り。", interpretation: "歩みを止めるな。", translation: "Take one step forward, and the winds will change." },
    { oracle: "水、形なくして道を知る。", interpretation: "古き縁が今を導く。", translation: "Wait patiently for the right moment." },
    { oracle: "風、北より来たる。", interpretation: "争わず、ただ佇むが良い。", translation: "Your thoughts have already reached their destination." },
    { oracle: "風、北より来たる。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "風、北より来たる。", interpretation: "沈黙が答えを導く。", translation: "Truth lies in the quiet." },
    { oracle: "心、波立つこと勿れ。", interpretation: "争わず、ただ佇むが良い。", translation: "It is time for reflection, not action." },
    { oracle: "水、形なくして道を知る。", interpretation: "沈黙が答えを導く。", translation: "Silence will guide you to the answer." },
    { oracle: "神、問いを与う。", interpretation: "真理は静けさの中にある。", translation: "Your thoughts have already reached their destination." },
    { oracle: "心、波立つこと勿れ。", interpretation: "歩みを止めるな。", translation: "Silence will guide you to the answer." },
    { oracle: "神、内に宿る。", interpretation: "一歩進めば風が変わる。", translation: "Silence will guide you to the answer." },
    { oracle: "風、北より来たる。", interpretation: "思いはすでに届いている。", translation: "Truth lies in the quiet." },
    { oracle: "星、流れて示すは縁。", interpretation: "慎重さが運を招く。", translation: "Silence will guide you to the answer." },
    { oracle: "風、北より来たる。", interpretation: "争わず、ただ佇むが良い。", translation: "Take one step forward, and the winds will change." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "行動よりも内観の時。", translation: "Truth lies in the quiet." },
    { oracle: "水、形なくして道を知る。", interpretation: "行動よりも内観の時。", translation: "Old ties will guide your present." },
    { oracle: "夢、深き淵に在り。", interpretation: "争わず、ただ佇むが良い。", translation: "It is time for reflection, not action." },
    { oracle: "神、問いを与う。", interpretation: "歩みを止めるな。", translation: "Your thoughts have already reached their destination." },
    { oracle: "月、影を照らす。", interpretation: "今は心静かに、機を待て。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "行動よりも内観の時。", translation: "Truth lies in the quiet." },
    { oracle: "夢、深き淵に在り。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "神、内に宿る。", interpretation: "古き縁が今を導く。", translation: "Silence will guide you to the answer." },
    { oracle: "神、内に宿る。", interpretation: "争わず、ただ佇むが良い。", translation: "Stand still without conflict." },
    { oracle: "星、流れて示すは縁。", interpretation: "歩みを止めるな。", translation: "Stand still without conflict." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "行動よりも内観の時。", translation: "Your thoughts have already reached their destination." },
    { oracle: "夢、深き淵に在り。", interpretation: "思いはすでに届いている。", translation: "It is time for reflection, not action." },
    { oracle: "夢、深き淵に在り。", interpretation: "慎重さが運を招く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "空、声なき声を放つ。", interpretation: "今は心静かに、機を待て。", translation: "Wait patiently for the right moment." },
    { oracle: "水、形なくして道を知る。", interpretation: "真理は静けさの中にある。", translation: "Wait patiently for the right moment." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Old ties will guide your present." },
    { oracle: "神、内に宿る。", interpretation: "古き縁が今を導く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "言、慎めば吉。", interpretation: "争わず、ただ佇むが良い。", translation: "Old ties will guide your present." },
    { oracle: "神、問いを与う。", interpretation: "歩みを止めるな。", translation: "Silence will guide you to the answer." },
    { oracle: "言、慎めば吉。", interpretation: "慎重さが運を招く。", translation: "It is time for reflection, not action." },
    { oracle: "空、声なき声を放つ。", interpretation: "古き縁が今を導く。", translation: "Old ties will guide your present." },
    { oracle: "空、声なき声を放つ。", interpretation: "慎重さが運を招く。", translation: "Stand still without conflict." },
    { oracle: "夢、深き淵に在り。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "空、声なき声を放つ。", interpretation: "一歩進めば風が変わる。", translation: "Take one step forward, and the winds will change." },
    { oracle: "心、波立つこと勿れ。", interpretation: "行動よりも内観の時。", translation: "Truth lies in the quiet." },
    { oracle: "月、影を照らす。", interpretation: "沈黙が答えを導く。", translation: "Truth lies in the quiet." },
    { oracle: "月、影を照らす。", interpretation: "今は心静かに、機を待て。", translation: "Your thoughts have already reached their destination." },
    { oracle: "時、未だ満ちず。", interpretation: "思いはすでに届いている。", translation: "Truth lies in the quiet." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "空、声なき声を放つ。", interpretation: "一歩進めば風が変わる。", translation: "Silence will guide you to the answer." },
    { oracle: "神、問いを与う。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "空、声なき声を放つ。", interpretation: "真理は静けさの中にある。", translation: "Silence will guide you to the answer." },
    { oracle: "空、声なき声を放つ。", interpretation: "思いはすでに届いている。", translation: "Your thoughts have already reached their destination." },
    { oracle: "時、未だ満ちず。", interpretation: "真理は静けさの中にある。", translation: "Wait patiently for the right moment." },
    { oracle: "静、兆しを孕む。", interpretation: "今は心静かに、機を待て。", translation: "Do not stop your steps." },
    { oracle: "静、兆しを孕む。", interpretation: "真理は静けさの中にある。", translation: "Truth lies in the quiet." },
    { oracle: "時、未だ満ちず。", interpretation: "今は心静かに、機を待て。", translation: "Truth lies in the quiet." },
    { oracle: "言、慎めば吉。", interpretation: "今は心静かに、機を待て。", translation: "Caution will lead to fortune." },
    { oracle: "神、問いを与う。", interpretation: "一歩進めば風が変わる。", translation: "Silence will guide you to the answer." },
    { oracle: "星、流れて示すは縁。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "時、未だ満ちず。", interpretation: "思いはすでに届いている。", translation: "Truth lies in the quiet." },
    { oracle: "夢、深き淵に在り。", interpretation: "争わず、ただ佇むが良い。", translation: "Caution will lead to fortune." },
    { oracle: "静、兆しを孕む。", interpretation: "一歩進めば風が変わる。", translation: "Stand still without conflict." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "It is time for reflection, not action." },
    { oracle: "時、未だ満ちず。", interpretation: "思いはすでに届いている。", translation: "Stand still without conflict." },
    { oracle: "風、北より来たる。", interpretation: "行動よりも内観の時。", translation: "Silence will guide you to the answer." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "沈黙が答えを導く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "心、波立つこと勿れ。", interpretation: "争わず、ただ佇むが良い。", translation: "Your thoughts have already reached their destination." },
    { oracle: "言、慎めば吉。", interpretation: "争わず、ただ佇むが良い。", translation: "Take one step forward, and the winds will change." },
    { oracle: "炎、内より燃ゆ。", interpretation: "今は心静かに、機を待て。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Wait patiently for the right moment." },
    { oracle: "心、波立つこと勿れ。", interpretation: "思いはすでに届いている。", translation: "Old ties will guide your present." },
    { oracle: "心、波立つこと勿れ。", interpretation: "真理は静けさの中にある。", translation: "Take one step forward, and the winds will change." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "争わず、ただ佇むが良い。", translation: "Stand still without conflict." },
    { oracle: "水、形なくして道を知る。", interpretation: "一歩進めば風が変わる。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "今は心静かに、機を待て。", translation: "Caution will lead to fortune." },
    { oracle: "夢、深き淵に在り。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "神、問いを与う。", interpretation: "慎重さが運を招く。", translation: "Truth lies in the quiet." },
    { oracle: "空、声なき声を放つ。", interpretation: "争わず、ただ佇むが良い。", translation: "Your thoughts have already reached their destination." },
    { oracle: "神、問いを与う。", interpretation: "慎重さが運を招く。", translation: "It is time for reflection, not action." },
    { oracle: "月、影を照らす。", interpretation: "行動よりも内観の時。", translation: "Wait patiently for the right moment." },
    { oracle: "静、兆しを孕む。", interpretation: "思いはすでに届いている。", translation: "Wait patiently for the right moment." },
    { oracle: "神、問いを与う。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "神、問いを与う。", interpretation: "慎重さが運を招く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "神、問いを与う。", interpretation: "歩みを止めるな。", translation: "Wait patiently for the right moment." },
    { oracle: "星、流れて示すは縁。", interpretation: "歩みを止めるな。", translation: "Your thoughts have already reached their destination." },
    { oracle: "空、声なき声を放つ。", interpretation: "思いはすでに届いている。", translation: "Do not stop your steps." },
    { oracle: "空、声なき声を放つ。", interpretation: "思いはすでに届いている。", translation: "Old ties will guide your present." },
    { oracle: "神、問いを与う。", interpretation: "行動よりも内観の時。", translation: "Your thoughts have already reached their destination." },
    { oracle: "神、内に宿る。", interpretation: "行動よりも内観の時。", translation: "Truth lies in the quiet." },
    { oracle: "言、慎めば吉。", interpretation: "思いはすでに届いている。", translation: "Old ties will guide your present." },
    { oracle: "風、北より来たる。", interpretation: "歩みを止めるな。", translation: "Old ties will guide your present." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "思いはすでに届いている。", translation: "Your thoughts have already reached their destination." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "真理は静けさの中にある。", translation: "Take one step forward, and the winds will change." },
    { oracle: "時、未だ満ちず。", interpretation: "沈黙が答えを導く。", translation: "Caution will lead to fortune." },
    { oracle: "時、未だ満ちず。", interpretation: "慎重さが運を招く。", translation: "Silence will guide you to the answer." },
    { oracle: "神、内に宿る。", interpretation: "真理は静けさの中にある。", translation: "Wait patiently for the right moment." },
    { oracle: "言、慎めば吉。", interpretation: "歩みを止めるな。", translation: "Caution will lead to fortune." },
    { oracle: "神、内に宿る。", interpretation: "今は心静かに、機を待て。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "争わず、ただ佇むが良い。", translation: "Your thoughts have already reached their destination." },
    { oracle: "心、波立つこと勿れ。", interpretation: "慎重さが運を招く。", translation: "Stand still without conflict." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Silence will guide you to the answer." },
    { oracle: "月、影を照らす。", interpretation: "思いはすでに届いている。", translation: "Stand still without conflict." },
    { oracle: "夢、深き淵に在り。", interpretation: "古き縁が今を導く。", translation: "Truth lies in the quiet." },
    { oracle: "時、未だ満ちず。", interpretation: "今は心静かに、機を待て。", translation: "Caution will lead to fortune." },
    { oracle: "夢、深き淵に在り。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "静、兆しを孕む。", interpretation: "一歩進めば風が変わる。", translation: "Silence will guide you to the answer." },
    { oracle: "時、未だ満ちず。", interpretation: "歩みを止めるな。", translation: "Take one step forward, and the winds will change." },
    { oracle: "夢、深き淵に在り。", interpretation: "沈黙が答えを導く。", translation: "Do not stop your steps." },
    { oracle: "炎、内より燃ゆ。", interpretation: "今は心静かに、機を待て。", translation: "Wait patiently for the right moment." },
    { oracle: "心、波立つこと勿れ。", interpretation: "古き縁が今を導く。", translation: "Truth lies in the quiet." },
    { oracle: "空、声なき声を放つ。", interpretation: "争わず、ただ佇むが良い。", translation: "Stand still without conflict." },
    { oracle: "時、未だ満ちず。", interpretation: "今は心静かに、機を待て。", translation: "Stand still without conflict." },
    { oracle: "水、形なくして道を知る。", interpretation: "争わず、ただ佇むが良い。", translation: "Wait patiently for the right moment." },
    { oracle: "神、内に宿る。", interpretation: "今は心静かに、機を待て。", translation: "Caution will lead to fortune." },
    { oracle: "炎、内より燃ゆ。", interpretation: "沈黙が答えを導く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "月、影を照らす。", interpretation: "今は心静かに、機を待て。", translation: "Stand still without conflict." },
    { oracle: "静、兆しを孕む。", interpretation: "慎重さが運を招く。", translation: "Caution will lead to fortune." },
    { oracle: "星、流れて示すは縁。", interpretation: "思いはすでに届いている。", translation: "It is time for reflection, not action." },
    { oracle: "時、未だ満ちず。", interpretation: "一歩進めば風が変わる。", translation: "Truth lies in the quiet." },
    { oracle: "時、未だ満ちず。", interpretation: "真理は静けさの中にある。", translation: "Silence will guide you to the answer." },
    { oracle: "空、声なき声を放つ。", interpretation: "行動よりも内観の時。", translation: "Wait patiently for the right moment." },
    { oracle: "言、慎めば吉。", interpretation: "古き縁が今を導く。", translation: "Wait patiently for the right moment." },
    { oracle: "夢、深き淵に在り。", interpretation: "今は心静かに、機を待て。", translation: "Wait patiently for the right moment." },
    { oracle: "神、問いを与う。", interpretation: "慎重さが運を招く。", translation: "Old ties will guide your present." },
    { oracle: "静、兆しを孕む。", interpretation: "真理は静けさの中にある。", translation: "Caution will lead to fortune." },
    { oracle: "言、慎めば吉。", interpretation: "今は心静かに、機を待て。", translation: "Stand still without conflict." },
    { oracle: "静、兆しを孕む。", interpretation: "一歩進めば風が変わる。", translation: "Stand still without conflict." },
    { oracle: "神、内に宿る。", interpretation: "思いはすでに届いている。", translation: "Truth lies in the quiet." },
    { oracle: "月、影を照らす。", interpretation: "争わず、ただ佇むが良い。", translation: "It is time for reflection, not action." },
    { oracle: "夢、深き淵に在り。", interpretation: "一歩進めば風が変わる。", translation: "It is time for reflection, not action." },
    { oracle: "月、影を照らす。", interpretation: "沈黙が答えを導く。", translation: "Stand still without conflict." },
    { oracle: "夢、深き淵に在り。", interpretation: "思いはすでに届いている。", translation: "Do not stop your steps." },
    { oracle: "心、波立つこと勿れ。", interpretation: "古き縁が今を導く。", translation: "Truth lies in the quiet." },
    { oracle: "神、内に宿る。", interpretation: "争わず、ただ佇むが良い。", translation: "Wait patiently for the right moment." },
    { oracle: "時、未だ満ちず。", interpretation: "真理は静けさの中にある。", translation: "Silence will guide you to the answer." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Truth lies in the quiet." },
    { oracle: "神、内に宿る。", interpretation: "思いはすでに届いている。", translation: "Old ties will guide your present." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "静、兆しを孕む。", interpretation: "争わず、ただ佇むが良い。", translation: "It is time for reflection, not action." },
    { oracle: "神、問いを与う。", interpretation: "一歩進めば風が変わる。", translation: "Truth lies in the quiet." },
    { oracle: "言、慎めば吉。", interpretation: "一歩進めば風が変わる。", translation: "Take one step forward, and the winds will change." },
    { oracle: "空、声なき声を放つ。", interpretation: "真理は静けさの中にある。", translation: "Silence will guide you to the answer." },
    { oracle: "夢、深き淵に在り。", interpretation: "思いはすでに届いている。", translation: "Truth lies in the quiet." },
    { oracle: "夢、深き淵に在り。", interpretation: "沈黙が答えを導く。", translation: "Do not stop your steps." },
    { oracle: "水、形なくして道を知る。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "神、問いを与う。", interpretation: "沈黙が答えを導く。", translation: "Truth lies in the quiet." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "心、波立つこと勿れ。", interpretation: "一歩進めば風が変わる。", translation: "Old ties will guide your present." },
    { oracle: "月、影を照らす。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "心、波立つこと勿れ。", interpretation: "行動よりも内観の時。", translation: "Stand still without conflict." },
    { oracle: "水、形なくして道を知る。", interpretation: "争わず、ただ佇むが良い。", translation: "Old ties will guide your present." },
    { oracle: "神、問いを与う。", interpretation: "行動よりも内観の時。", translation: "Old ties will guide your present." },
    { oracle: "風、北より来たる。", interpretation: "歩みを止めるな。", translation: "It is time for reflection, not action." },
    { oracle: "夢、深き淵に在り。", interpretation: "思いはすでに届いている。", translation: "Take one step forward, and the winds will change." },
    { oracle: "月、影を照らす。", interpretation: "一歩進めば風が変わる。", translation: "Take one step forward, and the winds will change." },
    { oracle: "星、流れて示すは縁。", interpretation: "争わず、ただ佇むが良い。", translation: "Silence will guide you to the answer." },
    { oracle: "神、問いを与う。", interpretation: "真理は静けさの中にある。", translation: "Stand still without conflict." },
    { oracle: "月、影を照らす。", interpretation: "真理は静けさの中にある。", translation: "Silence will guide you to the answer." },
    { oracle: "神、問いを与う。", interpretation: "沈黙が答えを導く。", translation: "It is time for reflection, not action." },
    { oracle: "空、声なき声を放つ。", interpretation: "古き縁が今を導く。", translation: "Do not stop your steps." },
    { oracle: "夢、深き淵に在り。", interpretation: "沈黙が答えを導く。", translation: "Caution will lead to fortune." },
    { oracle: "言、慎めば吉。", interpretation: "一歩進めば風が変わる。", translation: "Take one step forward, and the winds will change." },
    { oracle: "静、兆しを孕む。", interpretation: "一歩進めば風が変わる。", translation: "Old ties will guide your present." },
    { oracle: "炎、内より燃ゆ。", interpretation: "古き縁が今を導く。", translation: "Old ties will guide your present." },
    { oracle: "月、影を照らす。", interpretation: "争わず、ただ佇むが良い。", translation: "Silence will guide you to the answer." },
    { oracle: "言、慎めば吉。", interpretation: "沈黙が答えを導く。", translation: "Wait patiently for the right moment." },
    { oracle: "時、未だ満ちず。", interpretation: "思いはすでに届いている。", translation: "Take one step forward, and the winds will change." },
    { oracle: "時、未だ満ちず。", interpretation: "行動よりも内観の時。", translation: "Stand still without conflict." },
    { oracle: "静、兆しを孕む。", interpretation: "歩みを止めるな。", translation: "Take one step forward, and the winds will change." },
    { oracle: "神、問いを与う。", interpretation: "思いはすでに届いている。", translation: "Truth lies in the quiet." },
    { oracle: "時、未だ満ちず。", interpretation: "争わず、ただ佇むが良い。", translation: "Truth lies in the quiet." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "古き縁が今を導く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "沈黙が答えを導く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "静、兆しを孕む。", interpretation: "歩みを止めるな。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "行動よりも内観の時。", translation: "Your thoughts have already reached their destination." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "行動よりも内観の時。", translation: "Silence will guide you to the answer." },
    { oracle: "心、波立つこと勿れ。", interpretation: "沈黙が答えを導く。", translation: "Do not stop your steps." },
    { oracle: "水、形なくして道を知る。", interpretation: "沈黙が答えを導く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "今は心静かに、機を待て。", translation: "Wait patiently for the right moment." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "神、内に宿る。", interpretation: "歩みを止めるな。", translation: "Silence will guide you to the answer." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Stand still without conflict." },
    { oracle: "月、影を照らす。", interpretation: "沈黙が答えを導く。", translation: "Stand still without conflict." },
    { oracle: "言、慎めば吉。", interpretation: "沈黙が答えを導く。", translation: "Stand still without conflict." },
    { oracle: "心、波立つこと勿れ。", interpretation: "沈黙が答えを導く。", translation: "Silence will guide you to the answer." },
    { oracle: "月、影を照らす。", interpretation: "慎重さが運を招く。", translation: "Silence will guide you to the answer." },
    { oracle: "言、慎めば吉。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "言、慎めば吉。", interpretation: "争わず、ただ佇むが良い。", translation: "Wait patiently for the right moment." },
    { oracle: "心、波立つこと勿れ。", interpretation: "一歩進めば風が変わる。", translation: "Caution will lead to fortune." },
    { oracle: "水、形なくして道を知る。", interpretation: "思いはすでに届いている。", translation: "It is time for reflection, not action." },
    { oracle: "静、兆しを孕む。", interpretation: "真理は静けさの中にある。", translation: "Truth lies in the quiet." },
    { oracle: "心、波立つこと勿れ。", interpretation: "歩みを止めるな。", translation: "Silence will guide you to the answer." },
    { oracle: "心、波立つこと勿れ。", interpretation: "行動よりも内観の時。", translation: "Do not stop your steps." },
    { oracle: "星、流れて示すは縁。", interpretation: "沈黙が答えを導く。", translation: "Do not stop your steps." },
    { oracle: "闇、光を孕みて満つ。", interpretation: "一歩進めば風が変わる。", translation: "Wait patiently for the right moment." },
    { oracle: "言、慎めば吉。", interpretation: "沈黙が答えを導く。", translation: "Do not stop your steps." },
    { oracle: "夢、深き淵に在り。", interpretation: "思いはすでに届いている。", translation: "Take one step forward, and the winds will change." },
    { oracle: "空、声なき声を放つ。", interpretation: "慎重さが運を招く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "言、慎めば吉。", interpretation: "一歩進めば風が変わる。", translation: "Take one step forward, and the winds will change." },
    { oracle: "風、北より来たる。", interpretation: "真理は静けさの中にある。", translation: "Do not stop your steps." },
    { oracle: "心、波立つこと勿れ。", interpretation: "古き縁が今を導く。", translation: "Silence will guide you to the answer." },
    { oracle: "風、北より来たる。", interpretation: "慎重さが運を招く。", translation: "Stand still without conflict." },
    { oracle: "時、未だ満ちず。", interpretation: "慎重さが運を招く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "神、内に宿る。", interpretation: "一歩進めば風が変わる。", translation: "Your thoughts have already reached their destination." },
    { oracle: "月、影を照らす。", interpretation: "争わず、ただ佇むが良い。", translation: "Old ties will guide your present." },
    { oracle: "星、流れて示すは縁。", interpretation: "一歩進めば風が変わる。", translation: "Wait patiently for the right moment." },
    { oracle: "風、北より来たる。", interpretation: "古き縁が今を導く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "星、流れて示すは縁。", interpretation: "一歩進めば風が変わる。", translation: "Old ties will guide your present." },
    { oracle: "星、流れて示すは縁。", interpretation: "沈黙が答えを導く。", translation: "Silence will guide you to the answer." },
    { oracle: "時、未だ満ちず。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "水、形なくして道を知る。", interpretation: "争わず、ただ佇むが良い。", translation: "Silence will guide you to the answer." },
    { oracle: "星、流れて示すは縁。", interpretation: "行動よりも内観の時。", translation: "Take one step forward, and the winds will change." },
    { oracle: "神、内に宿る。", interpretation: "慎重さが運を招く。", translation: "Do not stop your steps." },
    { oracle: "空、声なき声を放つ。", interpretation: "行動よりも内観の時。", translation: "Old ties will guide your present." },
    { oracle: "風、北より来たる。", interpretation: "真理は静けさの中にある。", translation: "Caution will lead to fortune." },
    { oracle: "静、兆しを孕む。", interpretation: "思いはすでに届いている。", translation: "Do not stop your steps." },
    { oracle: "月、影を照らす。", interpretation: "古き縁が今を導く。", translation: "It is time for reflection, not action." },
    { oracle: "夢、深き淵に在り。", interpretation: "慎重さが運を招く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "月、影を照らす。", interpretation: "思いはすでに届いている。", translation: "Caution will lead to fortune." },
    { oracle: "時、未だ満ちず。", interpretation: "沈黙が答えを導く。", translation: "Wait patiently for the right moment." },
    { oracle: "静、兆しを孕む。", interpretation: "今は心静かに、機を待て。", translation: "Caution will lead to fortune." },
    { oracle: "水、形なくして道を知る。", interpretation: "慎重さが運を招く。", translation: "Take one step forward, and the winds will change." },
    { oracle: "心、波立つこと勿れ。", interpretation: "古き縁が今を導く。", translation: "Caution will lead to fortune." },
    { oracle: "月、影を照らす。", interpretation: "真理は静けさの中にある。", translation: "It is time for reflection, not action." },
    { oracle: "心、波立つこと勿れ。", interpretation: "慎重さが運を招く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "言、慎めば吉。", interpretation: "行動よりも内観の時。", translation: "Do not stop your steps." },
    { oracle: "水、形なくして道を知る。", interpretation: "行動よりも内観の時。", translation: "Take one step forward, and the winds will change." },
    { oracle: "心、波立つこと勿れ。", interpretation: "沈黙が答えを導く。", translation: "It is time for reflection, not action." },
    { oracle: "星、流れて示すは縁。", interpretation: "沈黙が答えを導く。", translation: "Your thoughts have already reached their destination." },
    { oracle: "風、北より来たる。", interpretation: "歩みを止めるな。", translation: "Take one step forward, and the winds will change." },
    { oracle: "星、流れて示すは縁。", interpretation: "古き縁が今を導く。", translation: "Stand still without conflict." },
    { oracle: "心、波立つこと勿れ。", interpretation: "行動よりも内観の時。", translation: "Wait patiently for the right moment." }
  ],
  runes: ["𐌕","𐌸","𐌔","𐍄","𓆑","𓂀","ⴰ","ⵔ","𐌻","𓇳"]
};
